name: spacephysics

channels:
  - conda-forge

dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - numpy
  - scipy
  - pandas
  - xlrd
  - xarray
  - matplotlib
  - ipympl
  - cartopy=0.24
  - viresclient
  - pip
  - pip:
      - ppigrf
      - pymsis
